# Generated by Django 4.2.7 on 2023-11-28 05:21

import Shop.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, default=39.99, max_digits=10, verbose_name='Price')),
                ('order_date', models.DateTimeField(auto_now=True, null=True)),
                ('date_update', models.DateTimeField(auto_now=True, null=True)),
                ('Weight', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Weight')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('Underway', 'Underway'), ('COMPLETE', 'COMPLETE'), ('Refunded', 'Refunded')], default='PENDING', max_length=13)),
                ('details', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=150, null=True, verbose_name='Slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to=Shop.models.upload_image_path, verbose_name='Product Image')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('status', models.BooleanField(blank=True, choices=[(True, 'Active'), (False, 'Inactive')], default=False, max_length=15, null=True)),
                ('priority', models.BooleanField(blank=True, default=False, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10, null=True)),
                ('date_start', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_end', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=0, default=39.99, max_digits=20)),
                ('featured', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=150, null=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to=Shop.models.upload_image_path, verbose_name='Product Image')),
                ('additional_image_1', models.ImageField(blank=True, max_length=500, null=True, upload_to=Shop.models.upload_image_path, verbose_name='Image_1')),
                ('additional_image_2', models.ImageField(blank=True, max_length=500, null=True, upload_to=Shop.models.upload_image_path, verbose_name='Image_2')),
                ('additional_image_3', models.ImageField(blank=True, max_length=500, null=True, upload_to=Shop.models.upload_image_path, verbose_name='Image_3')),
                ('additional_image_4', models.ImageField(blank=True, max_length=500, null=True, upload_to=Shop.models.upload_image_path, verbose_name='Image_4')),
                ('Like', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Like')),
                ('status', models.BooleanField(blank=True, choices=[(True, 'Active'), (False, 'Inactive')], default=False, max_length=15, null=True)),
                ('deleted', models.BooleanField(default=False, verbose_name='Product Deleted')),
                ('tags', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tags')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_update', models.DateTimeField(auto_now=True, null=True)),
                ('date_Deleted', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('viewed', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Viewed')),
                ('width', models.FloatField(blank=True, null=True, verbose_name='Width')),
                ('height', models.FloatField(blank=True, null=True, verbose_name='Height')),
                ('length', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('Weight', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Weight')),
                ('color', models.CharField(blank=True, choices=[('yellow', 'yellow'), ('green', 'green'), ('blue', 'blue'), ('red', 'red'), ('black', 'black'), ('white', 'white'), ('brown', 'brown'), ('pink', 'pink'), ('orange', 'orange')], default='black', max_length=15, null=True)),
                ('feedback_average', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Feedback average')),
                ('feedback_number', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Feedback number')),
                ('Advertising', models.CharField(blank=True, choices=[('New', 'New'), ('Hot', 'Hot')], default='New', max_length=13, null=True)),
                ('size', models.CharField(choices=[('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='L', max_length=13)),
                ('material', models.CharField(choices=[('wool', 'wool'), ('leather', 'leather'), ('cotton', 'cotton'), ('polyester', 'polyester')], default='wool', max_length=13)),
                ('category', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shop.category')),
            ],
        ),
        migrations.CreateModel(
            name='user_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('PhoneNumber', models.CharField(max_length=13)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(max_length=150)),
                ('post_code', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('Username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('password_update', models.CharField(max_length=50)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('roll', models.CharField(blank=True, choices=[('customer', 'customer'), ('seller', 'seller')], default='customer', max_length=13, null=True)),
                ('status_online', models.BooleanField(blank=True, choices=[(True, True), (False, False)], default=False, max_length=15, null=True)),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Slug')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=5000, null=True, verbose_name='comment')),
                ('status', models.BooleanField(blank=True, choices=[(True, True), (False, False)], default=False, max_length=15, null=True)),
                ('message', models.TextField(max_length=500)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.user_model')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('fee', models.FloatField(blank=True, default=0.0, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, default=False, max_length=15, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_update', models.DateTimeField(auto_now=True, null=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.user_model')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.discount'),
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.user_model'),
        ),
    ]
