# Generated by Django 4.2.7 on 2023-12-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='season',
            field=models.CharField(blank=True, choices=[('spring', 'spring'), ('summer', 'summer'), ('autumn', 'autumn'), ('winter', 'winter')], default='winter', max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sexuality',
            field=models.CharField(blank=True, choices=[('Women', 'Women'), ('Man', 'Man'), ('Both', 'Both')], default='Man', max_length=13, null=True),
        ),
    ]
