# Generated by Django 4.2.7 on 2023-12-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0008_orderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(to='Shop.orderproduct'),
        ),
    ]
