# Generated by Django 4.2.7 on 2023-12-02 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_alter_cart_user_alter_seller_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
    ]
