# Generated by Django 4.2.7 on 2023-12-02 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0011_orderproduct_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='items',
            new_name='product',
        ),
    ]
