# Generated by Django 4.2.7 on 2023-12-05 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0012_rename_items_cart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discounted_prices',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True),
        ),
    ]
